name: Deploy to the dev environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy-iac:
    uses: ./.github/workflows/workflow-iac.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}